version: '3.7'

services:
  postgres:
    container_name: postgres-db
    image: postgres:17.4-alpine
    ports:
      - $POSTGRES_PORT:5432
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - $ADMINER_PORT:8080
    depends_on:
      - postgres

  redis:
    container_name: redis
    image: redis
    ports:
      - $REDIS_PORT:6379

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    ports:
      - $MAILHOG_SMTP_PORT:1025
      - $MAILHOG_CLIENT_PORT:8025

  backend:
    container_name: backend
    build: .
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
      - mailhog
    command: sh -c "npx prisma migrate deploy && node dist/main.js"

networks:
  default:
    name: default-network